### ISSUE TITLE
Should packages be unlisted?

### ISSUE THREAD

**Issue by gep13** [Meir017/Cake.IntellisenseGenerator#1]
I was just wondering if you felt it might be worth unlisting the Cake.IntellisenseGenerator related packages that you have pushed to NuGet.org, now that we have shipped Cake.Bakery, and intellisense support is now provided via OmniSharp?

Is there anything that your implementation provides that isn't provided already?

Would love to discuss this further.  Thanks.

**Comment by Meir017** [comment]
You're right. I kind of forgot about this project...
I unlisted the package

**Comment by gep13** [comment]
@Meir017 that is great, thank you! I just think it will help minimise confusion if people find these packages. 😄

**Comment by gep13** [comment]
@Meir017 quick question...

I noticed that you unlisted this package:

https://www.nuget.org/packages/Cake.IntellisenseGenerator/

Does it make sense to also unlist this package:

https://www.nuget.org/packages/Cake.Intellisense.Core/

Thanks

**Comment by Meir017** [comment]
You're right

**Comment by gep13** [comment]
@Meir017 thank you for taking care of this.
